service: topic-service
package:
  version: 0.0.1-SNAPSHOT
  artifact: ./application/target/${self:service}-${self:package.version}-${self:provider}.jar
provider:
  name: aws
  runtime: java11
  region: us-east-2
  memorySize: 1024
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
  environment:
    APPLICATION_ENVIRONMENT: Dev
    CLOUD_REGION: US_East_2
functions:
  createTopic:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: topic/create
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: createFunction
  updateTopic:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: topic/update
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: updateFunction
  disableTopic:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: topic/disable
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: disableFunction
  getTopic:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: topic/findById
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: getFunction
  findAllTopic:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: topic/findAll
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: findAllFunction

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Topic
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
          - AttributeName: active
              AttributeType: B
        KeySchema:
          - AttributeName: code
            KeyType: HASH
          - AttributeName: active
              KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1